spring:
  application:
    name: store-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        #Query A 参数有A就行，Query B,C 参数B的值为C即可
        #实现针对于“http://localhost:88/?url=baidu”，转发到“https://www.baidu.com/hello”，
        #针对于“http://localhost:88/?url=qq”的请求，转发到“https://www.qq.com/hello”
        - id: baidu_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu

        - id: github_route
          uri: https://www.github.com
          predicates:
            - Query=url,github
#########################商品服务路由配置##########################################
#         注意!!!   精确的路由地址必须放到最前面   注意!!!
#########################商品服务路由配置##########################################
        - id: product_route
          uri: lb://store-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/$\{segment}

#########################仓储服务路由配置##########################################
        - id: ware_route
          uri: lb://store-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/$\{segment}


#########################三方服务路由配置##########################################
        - id: member_route
          uri: lb://store-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/$\{segment}

#########################会员服务路由配置##########################################
        - id: third_party_route
          uri: lb://story-thirdparty
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/?(?<segment>.*),/$\{segment}

########################后台服务路由配置##########################################
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/renren-fast/$\{segment}
########################商城首页路由##########################################
        - id: store_host_route
          uri: lb://store-product
          predicates:
            - Host=gulimall.com,item.gulimall.com
########################检索路由##########################################
        - id: store_host_search_route
          uri: lb://store-search
          predicates:
            - Host=search.gulimall.com
########################认证路由##########################################
        - id: store_auth_route
          uri: lb://store-auth-server
          predicates:
            - Host=auth.gulimall.com
########################购物车路由##########################################
        - id: store_cart_route
          uri: lb://store-cart
          predicates:
            - Host=cart.gulimall.com

server:
  port: 88