server:
  port: 20000
  servlet:
    session:
      timeout: 30m
spring:
  application:
    name: store-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.56.128
    port: 6379
  session:
    store-type: redis


